<a href="https://colab.research.google.com/github/rkrissada/100DayOfMLCode/blob/master/day_057_getting_started_with_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting started with TensorFlow

In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

1.13.1


## Adding two tensors

First, let's try doing this umsing numpy, the Python numneric package. numpy code is immediately eveluated.

In [2]:
a = np.array([5, 3, 8])
b = np.array([3, -1, 2])
c = np.add(a,b)

# 5+3, 3-1, 8+2

print(c)

[ 8  2 10]


The equivalent code in TensorFlow consists of two steps:

### Step 1: Build the graph

In [7]:
a = tf.constant([5, 3, 8])
b = tf.constant([3, -1, 2])
c = tf.add(a, b)

print(c)

Tensor("Add_4:0", shape=(3,), dtype=int32)


c is an Op ("Add") that returns a tensor of shape (3,) and holds int32. The shape is inferred from the computation graph.

Try the following in the cell above:

1. Change the 5 to 5.0, and similarly the other five numbers. What happens when you run this cell?
2. Add an extra number to a, but leave b at the original (3,) shape. What happens when you run this cell?
3. Change the code back to a version that works

### Step 2: Run the graph

In [9]:
with tf.Session() as sess:
  result = sess.run(c)
  print(result)

[ 8  2 10]


## Using a feed_dict

Same graph, but without hardcoding inputs at build stage

In [10]:
a = tf.placeholder(dtype=tf.int32, shape=(None,))
b = tf.placeholder(dtype=tf.int32, shape=(None,))
c = tf.add(a,b)

with tf.Session() as sess:
  result = sess.run(c, feed_dict={
      a: [5, 3, 8],
      b: [3, -1, 2]
  })
  print(result)

[ 8  2 10]
